spring:
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    password: 123456
    # 连接超时时间
    timeout: 10000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

# 应用服务端口配置
server:
  port: 8080

# 日志配置
logging:
  level:
    com.easy.lock: debug 